name: Pet Care Fastlane

on:
  push:
    branches: [main,GitHubActions_featurePetCareWorkflow]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
         gem uninstall bundler -aIx || true
         gem install bundler:1.17.2 fastlane -NV
         bundle _1.17.2_ install 

      - name: Set up environment
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: echo "Environment ready"

      - name: Build and Deploy to TestFlight
        run: bundle exec fastlane beta
